name: grant-pt
dependencies:
  - python=3.12
  - pip
  - jupyter
  - ipykernel
  - numpy
  - pandas
  - plotly
  - streamlit
  - scikit-learn
  - fastapi
  - pip:
      - "uvicorn[standard]"
      - -e .
